Style/CapitalizedSubject:
  Enabled: true
Layout/SubjectLength:
  # Max: 50
  Enabled: false
Metrics/BodyLength:
  # Min: 10
  Enabled: false
Layout/ImperativeSubject:
  Enabled: false
Layout/BodyRequired:
  Enabled: false
Layout/ValidGrammar:
  Enabled: false