Style/CapitalizedSubject:
  Enabled: true
# Style/CapitalizeBody:
#   Enabled: true
# Layout/SubjectLenght:
#   Max: 50
# Metrics/BodyLenght:
#   Min: 2
Layout/ImperativeSubject:
  Enabled: true
# Layout/BodyRequired:
#   Enabled: true
# Layout/ValidGrammar:
#   Enabled: true